# Generated by Django 4.0.1 on 2022-01-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
