# Generated by Django 4.0.1 on 2022-01-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='saved_by',
        ),
    ]
